version: '3.8'
services:
  worker-1:
    build: .
    container_name: worker-1
  worker-2:
    build: .
    container_name: worker-2
  worker-3:
    build: .
    container_name: worker-3
  worker-4:
    build: .
    container_name: worker-4
